ERROR   2022-07-04 10:10:35,156  D:\work_code\pytest-auto-api2\logs\error.log:conftest.py:133 异常用例数: 0
ERROR   2022-07-04 10:10:35,159  D:\work_code\pytest-auto-api2\logs\error.log:conftest.py:134 失败用例数: 0
ERROR   2022-07-04 10:31:28,175  D:\work_code\pytest-auto-api2\logs\error.log:conftest.py:133 异常用例数: 0
ERROR   2022-07-04 10:31:28,176  D:\work_code\pytest-auto-api2\logs\error.log:conftest.py:134 失败用例数: 0
ERROR   2022-07-04 13:36:15,947  D:\work_code\pytest-auto-api2\logs\error.log:mysqlControl.py:71 数据库连接失败，失败原因(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '* from ysq_test where name = '余少琪'' at line 1")
ERROR   2022-07-04 13:36:15,948  D:\work_code\pytest-auto-api2\logs\error.log:mysqlControl.py:122 数据库连接失败，失败原因'NoneType' object is not subscriptable
ERROR   2022-07-04 13:36:54,250  D:\work_code\pytest-auto-api2\logs\error.log:mysqlControl.py:122 数据库连接失败，失败原因断言的 sql 必须是查询的 sql
ERROR   2022-07-04 13:53:01,399  D:\work_code\pytest-auto-api2\logs\error.log:conftest.py:133 异常用例数: 0
ERROR   2022-07-04 13:53:01,400  D:\work_code\pytest-auto-api2\logs\error.log:conftest.py:134 失败用例数: 0
ERROR   2022-07-04 13:53:39,692  D:\work_code\pytest-auto-api2\logs\error.log:conftest.py:133 异常用例数: 0
ERROR   2022-07-04 13:53:39,692  D:\work_code\pytest-auto-api2\logs\error.log:conftest.py:134 失败用例数: 0
ERROR   2022-07-04 13:55:30,879  D:\work_code\pytest-auto-api2\logs\error.log:conftest.py:133 异常用例数: 0
ERROR   2022-07-04 13:55:30,879  D:\work_code\pytest-auto-api2\logs\error.log:conftest.py:134 失败用例数: 0
ERROR   2022-07-04 14:02:46,908  D:\work_code\pytest-auto-api2\logs\error.log:conftest.py:133 异常用例数: 0
ERROR   2022-07-04 14:02:46,909  D:\work_code\pytest-auto-api2\logs\error.log:conftest.py:134 失败用例数: 0
ERROR   2022-07-04 15:16:55,557  D:\work_code\pytest-auto-api2\logs\error.log:assertControl.py:135 JsonPath值获取失败$.errorCode
ERROR   2022-07-04 15:21:18,915  D:\work_code\pytest-auto-api2\logs\error.log:assertControl.py:135 JsonPath值获取失败$.errorCode
ERROR   2022-07-04 15:27:12,260  D:\work_code\pytest-auto-api2\logs\error.log:assertControl.py:135 JsonPath值获取失败$.errorCode
ERROR   2022-07-04 17:02:27,754  D:\work_code\pytest-auto-api2\logs\error.log:conftest.py:133 异常用例数: 0
ERROR   2022-07-04 17:02:27,755  D:\work_code\pytest-auto-api2\logs\error.log:conftest.py:134 失败用例数: 0
ERROR   2022-07-04 17:09:02,922  D:\work_code\pytest-auto-api2\logs\error.log:conftest.py:133 异常用例数: 0
ERROR   2022-07-04 17:09:02,923  D:\work_code\pytest-auto-api2\logs\error.log:conftest.py:134 失败用例数: 0
