ERROR   2022-05-23 13:46:36,081  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:131 异常用例数: 1
ERROR   2022-05-23 13:46:36,085  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:132 失败用例数: 0
ERROR   2022-05-23 13:48:14,654  C:\work\Study\pytest-auto-api2\logs\error.log:assertControl.py:135 JsonPath值获取失败$.errorCode
ERROR   2022-05-23 13:48:17,786  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:131 异常用例数: 0
ERROR   2022-05-23 13:48:17,786  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:132 失败用例数: 1
ERROR   2022-05-23 13:52:21,858  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:131 异常用例数: 0
ERROR   2022-05-23 13:52:21,858  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:132 失败用例数: 0
ERROR   2022-05-23 13:58:00,074  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:131 异常用例数: 0
ERROR   2022-05-23 13:58:00,074  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:132 失败用例数: 0
ERROR   2022-05-23 18:00:24,526  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:131 异常用例数: 0
ERROR   2022-05-23 18:00:24,527  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:132 失败用例数: 0
ERROR   2022-05-23 18:29:47,695  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:131 异常用例数: 0
ERROR   2022-05-23 18:29:47,695  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:132 失败用例数: 0
ERROR   2022-05-23 20:51:42,963  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:131 异常用例数: 0
ERROR   2022-05-23 20:51:42,963  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:132 失败用例数: 0
ERROR   2022-05-24 16:18:31,673  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:131 异常用例数: 0
ERROR   2022-05-24 16:18:31,673  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:132 失败用例数: 5
ERROR   2022-05-24 16:28:51,664  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:131 异常用例数: 0
ERROR   2022-05-24 16:28:51,664  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:132 失败用例数: 0
ERROR   2022-05-25 11:37:11,548  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:131 异常用例数: 0
ERROR   2022-05-25 11:37:11,550  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:132 失败用例数: 0
ERROR   2022-05-25 17:28:08,518  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:131 异常用例数: 6
ERROR   2022-05-25 17:28:08,519  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:132 失败用例数: 0
ERROR   2022-05-25 17:28:59,021  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:131 异常用例数: 0
ERROR   2022-05-25 17:28:59,021  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:132 失败用例数: 2
ERROR   2022-05-25 17:29:15,944  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:131 异常用例数: 0
ERROR   2022-05-25 17:29:15,944  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:132 失败用例数: 2
ERROR   2022-05-25 17:32:50,696  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:131 异常用例数: 0
ERROR   2022-05-25 17:32:50,697  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:132 失败用例数: 0
ERROR   2022-05-26 11:46:11,302  C:\work\Study\pytest-auto-api2\logs\error.log:mysqlControl.py:84 数据库连接失败，失败原因(1146, "Table 'bookshop.test_user' doesn't exist")
ERROR   2022-05-26 13:43:30,492  C:\work\Study\pytest-auto-api2\logs\error.log:mysqlControl.py:84 数据库连接失败，失败原因(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '$' at line 1")
ERROR   2022-05-26 13:46:40,369  C:\work\Study\pytest-auto-api2\logs\error.log:runTimeDecoratorl.py:24 
=================================================================================
测试用例执行时间较长，请关注.
函数运行时间:9825 ms
测试用例相关数据: {'response_data': {'data': {'desc': '', 'icon': '', 'id': 20569, 'link': 'https://gitee.com/yu_xiao_qi/pytest-auto-api2', 'name': '6781', 'order': 0, 'userId': 129462, 'visible': 1}, 'errorCode': 0, 'errorMsg': ''}, 'sql_data': {'sql': None}, 'yaml_data': {'method': 'POST', 'is_run': None, 'url': 'https://www.wanandroid.com/lg/collect/addtool/json', 'detail': '新增收藏网址接口', 'headers': {'cookie': 'loginUserName_wanandroid_com=18800000001;token_pass_wanandroid_com=5d9b90bcb70640183e09d1e755ead823;JSESSIONID=2E74EE8D2245315EBF94EA6AB11ABF28;loginUserName=18800000001;token_pass=5d9b90bcb70640183e09d1e755ead823;'}, 'requestType': 'DATE', 'data': {'name': 6781, 'link': 'https://gitee.com/yu_xiao_qi/pytest-auto-api2'}, 'dependence_case': False, 'dependence_case_data': {'dependence_case_data': None}, 'sql': None, 'assert': {'errorCode': {'jsonpath': '$.errorCode', 'type': '==', 'value': 0, 'AssertType': None}}, 'setup_sql': None, 'teardown': None, 'teardown_sql': None}, 'headers': {'cookie': 'loginUserName_wanandroid_com=18800000001;token_pass_wanandroid_com=5d9b90bcb70640183e09d1e755ead823;JSESSIONID=2E74EE8D2245315EBF94EA6AB11ABF28;loginUserName=18800000001;token_pass=5d9b90bcb70640183e09d1e755ead823;'}, 'cookie': None, 'res_time': 500.599, 'status_code': 200, 'teardown': None, 'teardown_sql': None}
=================================================================================
ERROR   2022-05-26 13:49:52,621  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:131 异常用例数: 0
ERROR   2022-05-26 13:49:52,621  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:132 失败用例数: 0
ERROR   2022-05-26 16:39:39,668  C:\work\Study\pytest-auto-api2\logs\error.log:assertControl.py:134 JsonPath值获取失败$.errorCode
ERROR   2022-05-26 16:46:05,833  C:\work\Study\pytest-auto-api2\logs\error.log:assertControl.py:134 JsonPath值获取失败$.errorCode
ERROR   2022-05-26 21:38:29,114  C:\work\Study\pytest-auto-api2\logs\error.log:assertControl.py:134 JsonPath值获取失败$.errorCode
ERROR   2022-05-26 21:59:13,613  C:\work\Study\pytest-auto-api2\logs\error.log:mysqlControl.py:38 数据库连接失败，失败原因(2003, "Can't connect to MySQL server on '106.14.1.241' (timed out)")
ERROR   2022-05-26 21:59:13,614  C:\work\Study\pytest-auto-api2\logs\error.log:mysqlControl.py:84 数据库连接失败，失败原因'MysqlDB' object has no attribute 'cur'
ERROR   2022-05-27 10:53:02,816  C:\work\Study\pytest-auto-api2\logs\error.log:assertControl.py:134 JsonPath值获取失败$.errorCode
ERROR   2022-05-27 10:53:06,233  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:131 异常用例数: 0
ERROR   2022-05-27 10:53:06,233  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:132 失败用例数: 1
ERROR   2022-05-27 10:55:23,857  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:131 异常用例数: 6
ERROR   2022-05-27 10:55:23,858  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:132 失败用例数: 0
ERROR   2022-05-27 10:55:40,830  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:131 异常用例数: 6
ERROR   2022-05-27 10:55:40,831  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:132 失败用例数: 0
ERROR   2022-05-27 10:56:31,542  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:131 异常用例数: 0
ERROR   2022-05-27 10:56:31,542  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:132 失败用例数: 0
ERROR   2022-05-27 10:59:15,091  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:131 异常用例数: 0
ERROR   2022-05-27 10:59:15,092  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:132 失败用例数: 0
ERROR   2022-05-27 16:53:27,348  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:131 异常用例数: 0
ERROR   2022-05-27 16:53:27,349  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:132 失败用例数: 0
ERROR   2022-05-27 16:55:41,886  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:131 异常用例数: 0
ERROR   2022-05-27 16:55:41,886  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:132 失败用例数: 0
ERROR   2022-05-27 16:57:23,739  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:131 异常用例数: 0
ERROR   2022-05-27 16:57:23,740  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:132 失败用例数: 0
ERROR   2022-05-27 16:58:01,839  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:131 异常用例数: 0
ERROR   2022-05-27 16:58:01,840  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:132 失败用例数: 0
ERROR   2022-05-27 16:59:51,929  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:131 异常用例数: 0
ERROR   2022-05-27 16:59:51,930  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:132 失败用例数: 0
ERROR   2022-05-27 17:00:45,797  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:131 异常用例数: 0
ERROR   2022-05-27 17:00:45,798  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:132 失败用例数: 0
ERROR   2022-05-27 17:01:28,963  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:131 异常用例数: 0
ERROR   2022-05-27 17:01:28,964  C:\work\Study\pytest-auto-api2\logs\error.log:conftest.py:132 失败用例数: 0
